"use strict";

const conn = require('./conn');

let res = conn.exec("create table demoNode(clave int primary key GENERATED BY DEFAULT AS IDENTITY, nombre varchar(100), telefono char(12))");
console.log(0 === res ? 'Tabla Creada' : 'Tabla no creada');
res = conn.exec("select * from demoNode");
console.log(res);
console.log("Datos a insertar { 'nombre': 'Ignacio Pacheco', 'tel' : '000000000000' }");
res = conn.exec("insert into demoNode (nombre, telefono) values ('Ignacio Pacheco', '000000000000')");
console.log(`Inserciones realizadas: ${ res }`);
res = conn.exec("select * from demoNode");
console.log(res);